/*
This file is automatically generated by a Perl script, constsJSC.pl.
The constants herein were copied from the following JavaScript files:

    /Users/jk/Documents/Programming/Projects/BookMacster/ExtensionsBrowser/Firefox/SheepSystemsFirefoxExtension/components/SheepSysJS_XPCOM.js

Do not edit.
*/

#include ".h"

char* const SHEEP_SYS_FIREFOX_EXTENSION_ID = "firefoxextension@sheepsystems.com" ; /* from SheepSysJS_XPCOM.js */
char* const SHEEP_SYS_JS_XPCOM_CONTRACT_ID = "@sheepsystems.com/SheepSysJS_XPCOM;1" ; /* from SheepSysJS_XPCOM.js */
