/*
This file is automatically generated by a Perl script, constsJSC.pl.
The constants herein were copied from the following JavaScript files:

    /Users/jk/Documents/Programming/Projects/BookMacster/ExtensionsBrowser/Firefox/SheepSystemsFirefoxExtension/components/SheepSysJS_XPCOM.js

Do not edit.
*/

#ifndef _INCLUDED__H_
#define _INCLUDED__H_

extern char* const SHEEP_SYS_FIREFOX_EXTENSION_ID ;
extern char* const SHEEP_SYS_JS_XPCOM_CONTRACT_ID ;

#endif
