@class BkmxDoc;
@class Watch;

extern NSString* const BkmxDocumentControllerErrorDomain ;

/*!
 @brief

 @details  The following information is from a 2003 Apple document which is
 no longer available, but I think still relevant.  At least the first "way"
 (Create your sub-class in the main nib file) works and that is what I am
 using.  I have read some cocoa-dev posts indicating that the second way
 may not work.

 ADC Home > Reference Library > Documentation > Cocoa > Design Guidelines
 > Document-Based Applications

 ## Creating a Subclass of NSDocumentController

 The NSDocumentController class keeps track of the first instance of
 NSDocumentController (or a custom subclass) that is created, and returns that
 instance from its sharedDocumentController method. To get your application to
 use your custom subclass of NSDocumentController, you must ensure your
 subclass is the first instance of NSDocumentController created when the
 application starts up. There are two ways to do this.

 ### Create your sub-class in the main nib file

 The main nib file is loaded by the application when it starts up. If you
 create an instance of you sub-class in the main nib file, the application
 will load it when it launches and will use it as the shared document
 controller. You should connect the application’s delegate outlet to the
 instance of your sub-class so the application can communicate with your
 document controller.

 ### Create an instance of your subclass in applicationWillFinishLaunching:

 The application will not ask for its shared document controller until after
 the applicationWillFinishLaunching: message is sent to its delegate.
 Therefore, you can create an instance of your sub-class of
 NSDocumentController in your application delegate’s
 applicationWillFinishLaunching: method and that instance will be set as the
 shared document controller.
 */
__attribute__((visibility("default"))) @interface BkmxDocumentController : NSDocumentController {
	NSInteger lastIssuedDocumentSequenceNumber ;
	BOOL m_isDuplicating ;
    BOOL m_skipAskingForClients ;
    NSMutableDictionary* _graveyardInfo;
    NSMutableSet* m_nowMigratingUrls;
}

@property (assign) BOOL isDuplicating ;
@property (assign) BOOL skipAskingForClients ;

/*!
 @brief    A document is slated to open
 
 @details  Once this is set to YES, it stays YES for the current app run.
 */
@property (readonly, assign) BOOL haveADoc;


- (BkmxDoc*)alreadyOpenDocWithUuid:(NSString*)uuid;

/*!
 @brief    Override base class declaration to indicate that our implementation
 passes our subclass BkmxDoc*, not NSDocument*, to the completion handler
 */
- (void)openDocumentWithContentsOfURL:(NSURL*)url
                              display:(BOOL)display
                    completionHandler:(void (^)(BkmxDoc* document,
                                                BOOL documentWasAlreadyOpen,
                                                NSError* error
                                                ))completionHandler ;

/*!
 @brief    Override replacement
 for -[NSDocumentController sharedDocumentController] to avoid
 typecasts.

 @details  Added in BookMacster 1.19.2
 */
+ (BkmxDocumentController*)sharedDocumentController ;

+ (NSSet*)documentDescriptionsFromWatches:(NSSet <Watch*>*)watches;
+ (NSString*)documentListFromWatches:(NSSet <Watch*>*)watches;

/*!
 @brief    Looks up a document by its uuid in user defaults, tries to
 resolve its path and returns the path if found
 
 @details  The total time required for this method to return may be up to
 (timeout + delay) * trials.
 
 @param    uuid  The uuid of the desired document.
 @param    appName  Name of the app which owns the desired document.  Should
 be constAppNameSmarky, constAppNameSynkmark, etc., or nil to search the user
 defaults of all three apps.
 @param    timeout  The timeout allowed to resolve the file alias, per trial
 @param    trials   The number of trials that are allowed
 @param    delay    Delay in seconds during which methods wait prior to a retry
 @param    error_p  If the document could not be opened, upon 
 return, will point to the NSError explaining the problem.
 @result   The requested path, or nil.
 */
- (NSString*)pathOfDocumentWithUuid:(NSString*)uuid
                            appName:(NSString*)appName
							timeout:(NSTimeInterval)timeout
                             trials:(NSInteger)trials
                              delay:(NSInteger)delay
							error_p:(NSError**)error_p ;
	
/*!
 @brief    Given an error generated by -pathOfDocumentWithUuid:::::,
 returns a comma-separated list of the document UUIDs that were found and
 searched by that method
 @details  Was a class method (which caused crash) until BookMacster 1.20.6.
 */
- (NSString*)uuidListFromError:(NSError*)error ;

/*!
 @brief    Looks up a document by its uuid in user defaults, tries to
 resolve its path and opens and invokes a completion handler.

 @param    uuid  The uuid of the desired document.
 @param    appName  The name of the app that owns the desired document. Should
 be one of constBkmxAppNameSmarky, constBkmxAppNameSynkmark, etc., or nil to
 default to "this" app.
 @param    display  If YES, the document will be displayed after
 opening.
 @param    aliaserTimeout  The timeout allowed to resolve the file path from
 its alias.  Note that there is an additional timeout for
 NSDocumentController to open the file before the completion handler is
 guaranteed to run.
*/
- (void)openDocumentWithUuid:(NSString*)uuid
                     appName:(NSString*)appName
                     display:(BOOL)display
              aliaserTimeout:(NSTimeInterval)aliaserTimeout
           completionHandler:(void(^)(BkmxDoc* bkmxDoc,
                                      NSURL* resolvedUrl,
                                      BOOL documentWasAlreadyOpen,
                                      NSError* error))completionHandler ;

/*!
 @brief    Opens a given document and displays its Settings > Syncing tab
 
 @param    info  A dictionary containing at least one key, constKeyAliasRecords,
 whose value is an array of alias records.
 @param    indexes  The document displayed will be that whose index in the
 given array of alias records is the firstIndex in this index set.
 
 */
- (IBAction)showSyncerssOfDocsAtIndexes:(NSIndexSet*)indexes
                                   info:(NSDictionary*)info ;

/*!
 @brief    Returns the path
    "/Users/who/Library/Application Support/BookMacster/Collections",
 first creating this directory if it does not exist.
 
 @details  If fails, will return nil and set the error_p if provided.
*/
- (NSString*)defaultDocumentFolderError_p:(NSError**)error_p ;


/*!
 @brief    Returns the next default filename, without the extension,
 by examining contents of
     "~/Library/Application Support/BookMacster/", first creating that 
 directory if it does not exist.
 
 @details  If fails, will return nil and set the error_p if provided.
 */
- (NSString *)nextDefaultFilenameError_p:(NSError**)error_p ;

- (NSURL*)nextDefaultDocumentUrl ;

/*!
 @brief    Our fancy wrapper for -[NSDocument openUntitledDocumentAndDisplay:error:],
 which makes and saves (sakes) a BkmxDoc document.

 @details  In addition to invoking super's -openUntitledDocumentAndDisplay:error:, this method:
 * Checks if it is OK to run the app
 * Runs a Save panel
 * Saves the new document
 * Sets the new document's skipAutomaticActions
 to YES
 @param    suggestedName  A suggested filename, which will appear in the
 Save panel, or nil to get a generic suggested filename.
 @param    display  Forwarded to -openUntitledDocumentAndDisplay:error: 
 @result   The new BkmxDoc.
*/
- (BkmxDoc*)makeUntitledDocumentWithSuggestedName:(NSString*)suggestedName
										 display:(BOOL)display
										 error_p:(NSError**)error_p ;

/*!
 @brief    NSDocumentController's -currentDocument returns nil if a
 document window is not *the* frontmost.  This method returns the document
 of the frontmost document window, and only returns nil if no document
 window is open.

 @details  Added in BookMacster 1.3.0 to fix "Internal error 395-1890 mercury
 contextual menu issue" in -[NSMenu(StarkContextual) addVisitItemsForBookmarks:]
*/
- (BkmxDoc*)frontmostDocument ;

/*!
 @brief    Returns whether or not a given error indicates that the actual fault
 may be that the app version is too old to open a document, which means that
 the relevant document may in fact be OK and should not be forgotten, trashed,
 etc.
 
 @details  This method knows the codes and domains of the errors for which it
 should return YES.  If 'error' is some other kind of error, for example an
 error which his not related to document opening, this method will return NO.
*/
- (BOOL)indicatesNoDataModelError:(NSError*)error ;

/*!
 @brief    If documents have operations in their queue, returns a low-severity
 error saying so; otherwise, returns nil.
 */
- (NSError*)operationsInProgressErrorWithCode:(NSInteger)code
                                  ignoreQueue:(NSOperationQueue*)ignoredQueue ;

- (NSString*)shoeboxDocumentBaseName ;

- (void)shoeboxDocumentForcibly:(BOOL)forcibly
              completionHandler:(void(^)(BkmxDoc*))completionHandler ;

- (NSString*)shoeboxDocumentPathError_p:(NSError**)error_p ;

- (BOOL)fileUrlSaysThisIsAShoebox:(NSDocument*)bkmxDoc;

- (void)forgetAndTrashDocWithUuid:(NSString*)uuid
                          fileUrl:(NSURL*)fileUrl ;

@end
