/*
This file WAS automatically generated by a Perl script, constsJSC.pl.
The constants herein were copied from the following JavaScript files:

    /Users/jk/Documents/Programming/Projects/BkmkMgrs/ExtensionsBrowser/Firefox/sheepsystemsmenuextension/components/SheepSysJS_XPCOM.js

But that script is broken
*/

#ifndef _INCLUDED_CONSTSFROMJAVASCRIPT_H_
#define _INCLUDED_CONSTSFROMJAVASCRIPT_H_

extern char* const SHEEP_SYS_FIREFOX_MENU_EXTENSION_ID ;
extern char* const SHEEP_SYS_FIREFOX_SYNC_EXTENSION_ID ;
extern char* const SHEEP_SYS_JS_XPCOM_CONTRACT_ID ;

#endif
