import Foundation

/**
    Provides a convenient initializer for a particular flavor of NSError,
 although my NSError categories in CategoriesObjC are pretty convenient
 too.
 
 I tried to make this instead an extension on NSError, but could not remove
 all compiler errors due to a couple of "gotchas" regarding convenience
 initializers needing to call super.init() and instance variableds being
 readonly.  Oh well, I learned some more Swift from writing this.
 */
@objc
class BkmxAgentRunnerError: NSError, @unchecked Sendable {
    enum What: Int {
        case couldNotEvenLaunchAgentRunner = 3303
        case couldNotReadLogFileFromAgentRunner = 3304
    }
    
    init(_ what: What, attempting: String? = nil,
         bundleIdentifier: String? = nil,
         underlying: Error? = nil,
         log: String? = nil,
         runnerReturnValue: Int? = nil
    ) {
        var localizedDescription: String = "Sorry, no descripion"

        switch what {
        case .couldNotReadLogFileFromAgentRunner:
            localizedDescription = NSLocalizedString(
                "Could not read log file which should have ben generated by BkmxAgentRunner",
                comment: "what it says"
            )
        case .couldNotEvenLaunchAgentRunner:
            localizedDescription = NSLocalizedString(
                "Could not even launch the agent runner",
                comment: "what it says"
            )
        }

        var userInfo: Dictionary<String, Any> = Dictionary()
        userInfo[NSLocalizedDescriptionKey] = localizedDescription
        let underlyingNSError = underlying as? NSError
        userInfo[NSUnderlyingErrorKey] = underlyingNSError
        super.init(domain:"BkmxAgentRunnerErrorDomain",
                   code: what.rawValue,
                   userInfo: userInfo)
    }
    
    /**
     Even though this is a rather redundant subclass which does not even
     add any instance vars, the compiler complains without this trivial
     implementation, I guess because NSError conforms to NSSecureCoding
     which in turn inherits from NSCoding which requires init(coder:)
     */
    required init?(coder: NSCoder) {
        super.init(coder: coder)
    }
}
